package com.pedro.tone3000m1.domain.model

internal data class PresetData(
    val slot: Int,
    val modelPath: String,
    val modelName: String,
    val modelSize: String,
    val toneId: String?,
    val toneTitle: String?,
    val moduleType: String = "AMP",
    val inputGainDb: Float,
    val outputGainDb: Float,
    val inputChannel: Int,
    val outputPair: Int,
    val gateEnabled: Boolean,
    val gateThresholdDb: Float,
    val eqLowDb: Float,
    val eqMidDb: Float,
    val eqHighDb: Float,
    val namBypass: Boolean,
    val namGainDb: Float,
    val namInGainDb: Float,
    val namMix: Float,
    val namEqDb: List<Float>,
    val namEqPre: Boolean,
    val namNormalize: Boolean,
    val namA2Full: Boolean,
    val extraNamChainJson: String,
    val cabinetIrPath: String?,
    val cabinetIrTitle: String,
    val cabinetIrToneId: String,
    val cabinetIrModuleType: String,
    val cabinetIrBypass: Boolean,
    val cabinetIrPosition: Int,
    val cabinetIrInGain: Float,
    val cabinetIrOutGain: Float,
    val cabinetIrMix: Float,
    val cabinetIrEqPre: Boolean,
    val cabinetIrEqDb: List<Float>,
)
