package com.pedro.tone3000m1.ui.model

internal data class UiModule(
    val id: String,
    val type: String,
    val name: String,
    val moduleType: String = "AMP",
    val index: Int = -1,
    val bypass: Boolean = false,
    val gainDb: Float = -15f,
    val inGainDb: Float = 0f,
    val mix: Float = 1f,
    val eqEnabled: Boolean = true,
    val eqPre: Boolean = false,
    val normalize: Boolean = true,
    val a2Full: Boolean = false,
    val eqBands: List<Float> = List(6) { 0f },
    val nativeEffect: Int = 0,
    val nativePosition: Int = 5,
    val nativeParam1: Float = 350f,
    val nativeParam2: Float = 0.35f,
    val nativeParam3: Float = 12f,
    val nativeOutputGainDb: Float = 0f,
    val fxTempoSync: Boolean = false,
    val fxSyncLeftNote: String = "1/4",
    val fxSyncRightNote: String = "1/8.",
)

internal data class UiPreset(val slot: Int, val label: String, val saved: Boolean)

internal data class UiLocalNamCapture(
    val path: String,
    val modelName: String,
    val modelSize: String,
    val toneTitle: String,
    val toneId: String,
    val imageUrl: String,
    val moduleType: String,
    val modelId: Long = 0L,
)

internal data class PicoloUiState(
    val running: Boolean = false,
    val inputDbFs: Float? = null,
    val outputDbFs: Float? = null,
    val bypass: Boolean = false,
    val modelName: String = "No capture loaded",
    val toneTitle: String = "",
    val activePresetSlot: Int = 0,
    val globalTapTempoBpm: Float = 120f,
    val device: String = "Audio interface: auto detect",
    val inputGain: Float = 0f,
    val outputGain: Float = 0f,
    val gateEnabled: Boolean = false,
    val gateThreshold: Float = -65f,
    val eqEnabled: Boolean = true,
    val eqLow: Float = 0f,
    val eqMid: Float = 0f,
    val eqHigh: Float = 0f,
    val cabinetLoaded: Boolean = false,
    val cabinetName: String = "",
    val cabinetType: String = "IR",
    val cabinetInGain: Float = 0f,
    val cabinetOutGain: Float = 0f,
    val cabinetMix: Float = 1f,
    val cabinetEqEnabled: Boolean = true,
    val cabinetEqPre: Boolean = false,
    val cabinetEq: List<Float> = List(6) { 0f },
    val modules: List<UiModule> = emptyList(),
    val presets: List<UiPreset> = emptyList(),
    val localNamCaptures: List<UiLocalNamCapture> = emptyList(),
    val selectedModuleType: String = "AMP",
    val status: String = "Ready",
    val loadingMessage: String? = null,
    val routing: String = "",
    val processingPercent: Float? = null,
    val processingAvgUs: Float? = null,
    val processingMaxUs: Float = 0f,
    val processingBudgetUs: Float = 0f,
    val overBudgetCount: Long = 0,
    val audioIoErrors: Long = 0,
)
